Fix mac action build (#1498)
* Fix mac action build

* Fix mac action build

diff --git a/.github/workflows/ci-master.yml b/.github/workflows/ci-master.yml
--- a/.github/workflows/ci-master.yml
+++ b/.github/workflows/ci-master.yml
@@ -174,7 +174,14 @@ jobs:
     - name: Use Xcode instead of Command Line Tools
       run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
     - name: Install Required Packages
-      run: brew install automake coreutils pkg-config python-setuptools
+      run: |
+        if ! command -v pkg-config &> /dev/null; then
+          echo "pkg-config not found, installing..."
+          brew install pkg-config
+        else
+          echo "pkg-config is already installed"
+        fi
+        brew install automake coreutils python-setuptools
       # Workaround for macOS: https://github.com/actions/runner/issues/2958
     - name: Install setuptools
       run: sudo -H pip install setuptools
